service: serverless-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
        cors: { origin: true }

plugins:
  - serverless-offline
  - serverless-jest-plugin